/* ============================================================
   ORACLE JAVA BOT - FAKE DATA
   ============================================================ */

/* ============================================================
   1. ROLES
   ============================================================ */
INSERT INTO ROLES (ROLE_NAME, DESCRIPTION)
VALUES ('MANAGER',   'Gestor de proyectos y sprints');

INSERT INTO ROLES (ROLE_NAME, DESCRIPTION)
VALUES ('DEVELOPER', 'Desarrollador asignado a tareas');

/* ============================================================
   2. TEAMS
   ============================================================ */
INSERT INTO TEAMS (NAME, DESCRIPTION)
VALUES ('Backend Team',  'Equipo de desarrollo de servicios y APIs');

INSERT INTO TEAMS (NAME, DESCRIPTION)
VALUES ('Frontend Team', 'Equipo de desarrollo de interfaces');

/* ============================================================
   3. USERS
   ============================================================ */
INSERT INTO USERS (FULL_NAME, EMAIL, TELEGRAM_ID, ROLE_ID, TEAM_ID, STATUS)
VALUES ('Ana Torres',      'ana.torres@empresa.com',      '@anatorres',     1, 1, 'ACTIVE');

INSERT INTO USERS (FULL_NAME, EMAIL, TELEGRAM_ID, ROLE_ID, TEAM_ID, STATUS)
VALUES ('Luis Ramirez',    'luis.ramirez@empresa.com',    '@luisramirez',   2, 1, 'ACTIVE');

INSERT INTO USERS (FULL_NAME, EMAIL, TELEGRAM_ID, ROLE_ID, TEAM_ID, STATUS)
VALUES ('Sofia Rios',      'sofia.rios@empresa.com',      '@sofiaros',      2, 2, 'ACTIVE');

INSERT INTO USERS (FULL_NAME, EMAIL, TELEGRAM_ID, ROLE_ID, TEAM_ID, STATUS)
VALUES ('Maria Gutierrez', 'maria.gutierrez@empresa.com', '@mariagutierrez',2, 1, 'ACTIVE');

INSERT INTO USERS (FULL_NAME, EMAIL, TELEGRAM_ID, ROLE_ID, TEAM_ID, STATUS)
VALUES ('Laura Jimenez',   'laura.jimenez@empresa.com',   '@laurajimenez',  1, 2, 'ACTIVE');

/* ============================================================
   4. USER_CREDENTIALS
   ============================================================ */
INSERT INTO USER_CREDENTIALS (USER_ID, USERNAME, PASSWORD_HASH, PASSWORD_SALT, FAILED_ATTEMPTS, ACCOUNT_LOCKED)
VALUES (1, 'ana.torres',
        'b3a8e0e1f9ab1827e1f18c4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4',
        'SALT_B2C3D4E5F6A1', 0, 'N');

INSERT INTO USER_CREDENTIALS (USER_ID, USERNAME, PASSWORD_HASH, PASSWORD_SALT, FAILED_ATTEMPTS, ACCOUNT_LOCKED)
VALUES (2, 'luis.ramirez',
        'c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5',
        'SALT_C3D4E5F6A1B2', 0, 'N');

INSERT INTO USER_CREDENTIALS (USER_ID, USERNAME, PASSWORD_HASH, PASSWORD_SALT, FAILED_ATTEMPTS, ACCOUNT_LOCKED)
VALUES (3, 'sofia.rios',
        'd5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6',
        'SALT_D4E5F6A1B2C3', 0, 'N');

INSERT INTO USER_CREDENTIALS (USER_ID, USERNAME, PASSWORD_HASH, PASSWORD_SALT, FAILED_ATTEMPTS, ACCOUNT_LOCKED)
VALUES (4, 'maria.gutierrez',
        'f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8',
        'SALT_F6A1B2C3D4E5', 0, 'N');

INSERT INTO USER_CREDENTIALS (USER_ID, USERNAME, PASSWORD_HASH, PASSWORD_SALT, FAILED_ATTEMPTS, ACCOUNT_LOCKED)
VALUES (5, 'laura.jimenez',
        'b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0',
        'SALT_B6C1D2E3F4A5', 0, 'N');

/* ============================================================
   5. SPRINTS
   ============================================================ */
INSERT INTO SPRINTS (NAME, START_DATE, END_DATE, STATUS)
VALUES ('Alpha - Sprint 1', DATE '2025-01-06', DATE '2025-01-19', 'CLOSED');


INSERT INTO SPRINTS (NAME, START_DATE, END_DATE, STATUS)
VALUES ('Alpha - Sprint 2', DATE '2025-01-20', DATE '2025-02-02', 'CLOSED');

INSERT INTO SPRINTS (NAME, START_DATE, END_DATE, STATUS)
VALUES ('Alpha - Sprint 3', DATE '2025-02-03', DATE '2025-02-16', 'ACTIVE');

INSERT INTO SPRINTS (NAME, START_DATE, END_DATE, STATUS)
VALUES ('Beta - Sprint 1', DATE '2025-01-13', DATE '2025-01-26', 'CLOSED');

INSERT INTO SPRINTS (NAME, START_DATE, END_DATE, STATUS)
VALUES ('Beta - Sprint 2', DATE '2025-01-27', DATE '2025-02-09', 'ACTIVE');

/* ============================================================
   6. PROJECTS
   ============================================================ */
INSERT INTO PROJECTS (NAME, DESCRIPTION, MANAGER_ID, STATUS)
VALUES ('Proyecto Alpha',
        'Plataforma de gestión de tareas con integración de bot Telegram',
        1, 'ACTIVE');

INSERT INTO PROJECTS (NAME, DESCRIPTION, MANAGER_ID, STATUS)
VALUES ('Proyecto Beta',
        'Sistema de monitoreo de KPIs y reportes automatizados',
        5, 'ACTIVE');

INSERT INTO PROJECTS (NAME, DESCRIPTION, MANAGER_ID, STATUS)
VALUES ('Proyecto Gamma',
        'Migración de infraestructura a contenedores',
        1, 'ON_HOLD');

/* ============================================================
   7. PROJECT_SPRINTS
   ============================================================ */
INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE)
VALUES (1, 1, 1, 'N');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE)
VALUES (1, 2, 2, 'N');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE)
VALUES (1, 3, 3, 'Y');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE)
VALUES (2, 4, 1, 'N');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE)
VALUES (2, 5, 2, 'Y');

/* ============================================================
   8. PROJECT_MEMBERS
   ============================================================ */
-- Proyecto Alpha
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (1, 1, 'MANAGER');
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (1, 2, 'DEVELOPER');
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (1, 3, 'DEVELOPER');
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (1, 4, 'DEVELOPER');

-- Proyecto Beta
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (2, 5, 'MANAGER');
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (2, 2, 'DEVELOPER');
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (2, 4, 'DEVELOPER');

-- Proyecto Gamma
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (3, 1, 'MANAGER');
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT) VALUES (3, 2, 'DEVELOPER');

/* ============================================================
   9. TASKS
   ============================================================ */

-- ── Proyecto Alpha / Sprint 1 (CLOSED) ─────────────────────
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 1, 'Configurar base de datos Oracle',
        'Instalación y configuración inicial de Oracle 19c',
        'COMPLETED', 'DONE', 'HIGH', 1, 2, DATE '2025-01-15');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 1, 'Diseñar modelo entidad-relación',
        'Crear el ERD completo del sistema',
        'COMPLETED', 'DONE', 'HIGH', 1, 4, DATE '2025-01-17');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 1, 'Setup entorno de desarrollo',
        'Configurar Docker, JDK 17 y Maven',
        'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2025-01-18');

-- ── Proyecto Alpha / Sprint 2 (CLOSED) ─────────────────────
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 2, 'Implementar autenticación JWT',
        'Endpoints de login, logout y refresh token',
        'COMPLETED', 'DONE', 'HIGH', 1, 2, DATE '2025-01-28');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 2, 'CRUD de usuarios',
        'Endpoints REST para gestión de usuarios',
        'COMPLETED', 'DONE', 'HIGH', 1, 4, DATE '2025-01-30');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 2, 'Pruebas de integración autenticación',
        'Suite de pruebas para flujo de autenticación',
        'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2025-02-01');

-- Tarea arrastrada Sprint 2 → Sprint 3
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 3, 'Integración con Telegram Bot API',
        'Configurar webhook y handlers básicos del bot',
        'SPRINT', 'IN_PROGRESS', 'HIGH', 1, 2, DATE '2025-02-14');

-- ── Proyecto Alpha / Sprint 3 (ACTIVE) ─────────────────────
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 3, 'Módulo de notificaciones',
        'Enviar alertas por Telegram cuando se actualice una tarea',
        'SPRINT', 'PENDING', 'MEDIUM', 1, 4, DATE '2025-02-16');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 3, 'Dashboard de KPIs frontend',
        'Pantalla principal con gráficas de métricas del proyecto',
        'SPRINT', 'IN_PROGRESS', 'HIGH', 1, 3, DATE '2025-02-15');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (1, 3, 'Corrección de bug en login OAuth',
        'El token expira prematuramente en algunos clientes',
        'SPRINT', 'REOPENED', 'HIGH', 1, 2, DATE '2025-02-13');

-- ── Proyecto Alpha / Backlog ────────────────────────────────
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY)
VALUES (1, NULL, 'Implementar rate limiting en API',
        'Protección contra abuso de endpoints públicos',
        'BACKLOG', 'PENDING', 'MEDIUM', 1);

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY)
VALUES (1, NULL, 'Documentación Swagger / OpenAPI',
        'Documentar todos los endpoints REST',
        'BACKLOG', 'PENDING', 'LOW', 1);

-- ── Proyecto Beta / Sprint 4 (CLOSED) ──────────────────────
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (2, 4, 'Definir catálogo de KPI_TYPES',
        'Registrar todos los tipos de KPI en la base de datos',
        'COMPLETED', 'DONE', 'HIGH', 5, 4, DATE '2025-01-24');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (2, 4, 'Job de cálculo nocturno de KPIs',
        'Implementar scheduler para insertar KPI_VALUES al cierre de sprint',
        'COMPLETED', 'DONE', 'HIGH', 5, 2, DATE '2025-01-25');

-- ── Proyecto Beta / Sprint 5 (ACTIVE) ──────────────────────
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (2, 5, 'Endpoint GET /api/dashboard',
        'Retornar todos los KPIs más recientes en una sola llamada',
        'SPRINT', 'IN_PROGRESS', 'HIGH', 5, 4, DATE '2025-02-07');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE)
VALUES (2, 5, 'Integración con agente de monitoreo CPU/RAM',
        'Recibir métricas de infraestructura vía push',
        'SPRINT', 'PENDING', 'MEDIUM', 5, 2, DATE '2025-02-09');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY)
VALUES (2, NULL, 'Migrar a MongoDB (descartado)',
        'Evaluación de migración - cancelada por decisión arquitectural',
        'BACKLOG', 'CANCELLED', 'LOW', 5);

-- Tarea global en backlog
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY)
VALUES (NULL, NULL, 'Investigar integración con Jira',
        'Evaluar si importar tareas desde Jira es viable',
        'BACKLOG', 'PENDING', 'LOW', 1);

/* ============================================================
   10. TASK_STATUS_HISTORY
   ============================================================ */
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (1, 'PENDING', 'IN_PROGRESS', 2, TIMESTAMP '2025-01-07 09:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (1, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2025-01-14 17:30:00');

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (2, 'PENDING', 'IN_PROGRESS', 4, TIMESTAMP '2025-01-08 10:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (2, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2025-01-16 16:00:00');

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (3, 'PENDING', 'IN_PROGRESS', 3, TIMESTAMP '2025-01-10 11:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (3, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2025-01-17 15:00:00');

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (4, 'PENDING', 'IN_PROGRESS', 2, TIMESTAMP '2025-01-21 09:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (4, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2025-01-27 18:00:00');

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (5, 'PENDING', 'IN_PROGRESS', 4, TIMESTAMP '2025-01-22 10:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (5, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2025-01-29 17:00:00');

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (6, 'PENDING', 'IN_PROGRESS', 3, TIMESTAMP '2025-01-24 09:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (6, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2025-01-31 16:30:00');

-- Tarea 7: arrastrada Sprint 2 → Sprint 3
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (7, 'PENDING', 'IN_PROGRESS', 2, TIMESTAMP '2025-01-27 11:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (7, 'IN_PROGRESS', 'PENDING', 1, TIMESTAMP '2025-02-02 18:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (7, 'PENDING', 'IN_PROGRESS', 2, TIMESTAMP '2025-02-04 09:00:00');

-- Tarea 10: PENDING → IN_PROGRESS → DONE → REOPENED
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (10, 'PENDING', 'IN_PROGRESS', 2, TIMESTAMP '2025-02-04 10:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (10, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2025-02-05 15:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (10, 'DONE', 'REOPENED', 3, TIMESTAMP '2025-02-06 11:00:00'); 

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (14, 'PENDING', 'IN_PROGRESS', 2, TIMESTAMP '2025-01-14 09:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (14, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2025-01-24 17:00:00');

INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT)
VALUES (17, 'PENDING', 'CANCELLED', 5, TIMESTAMP '2025-01-15 14:00:00');

/* ============================================================
   11. TASK_SPRINT_HISTORY
   ============================================================ */
INSERT INTO TASK_SPRINT_HISTORY (TASK_ID, OLD_SPRINT_ID, NEW_SPRINT_ID, CHANGED_BY, CHANGED_AT)
VALUES (1, NULL, 1, 1, TIMESTAMP '2025-01-06 08:00:00');

INSERT INTO TASK_SPRINT_HISTORY (TASK_ID, OLD_SPRINT_ID, NEW_SPRINT_ID, CHANGED_BY, CHANGED_AT)
VALUES (7, NULL, 2, 1, TIMESTAMP '2025-01-20 08:00:00');

INSERT INTO TASK_SPRINT_HISTORY (TASK_ID, OLD_SPRINT_ID, NEW_SPRINT_ID, CHANGED_BY, CHANGED_AT)
VALUES (7, 2, 3, 1, TIMESTAMP '2025-02-03 08:00:00');

INSERT INTO TASK_SPRINT_HISTORY (TASK_ID, OLD_SPRINT_ID, NEW_SPRINT_ID, CHANGED_BY, CHANGED_AT)
VALUES (10, NULL, 3, 1, TIMESTAMP '2025-02-03 09:00:00');

INSERT INTO TASK_SPRINT_HISTORY (TASK_ID, OLD_SPRINT_ID, NEW_SPRINT_ID, CHANGED_BY, CHANGED_AT)
VALUES (13, NULL, 4, 5, TIMESTAMP '2025-01-13 08:00:00');

INSERT INTO TASK_SPRINT_HISTORY (TASK_ID, OLD_SPRINT_ID, NEW_SPRINT_ID, CHANGED_BY, CHANGED_AT)
VALUES (14, NULL, 4, 5, TIMESTAMP '2025-01-13 08:00:00');

/* ============================================================
   12. KPI_TYPES
   ============================================================ */
INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('TAREAS_COMPLETADAS_SPRINT',     'DELIVERY',    'count',   'Tareas con STATUS=DONE por sprint');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('CUMPLIMIENTO_SPRINT',           'DELIVERY',    'percent', 'Tareas done / total tareas del sprint');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('TAREAS_REABIERTAS',             'QUALITY',     'count',   'Tareas que pasaron a REOPENED en el sprint');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('ACTUALIZACION_TAREAS_DIA',      'ACTIVITY',    'percent', 'Tareas actualizadas hoy / total activas');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('TRAZABILIDAD_TAREAS',           'QUALITY',     'count',   'Tareas sin ningún registro en TASK_STATUS_HISTORY');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('DESPLIEGUES_PRODUCCION_SPRINT', 'DEVOPS',      'count',   'Deploys a PRODUCTION exitosos por sprint');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('MTTR',                          'DEVOPS',      'minutes', 'Tiempo medio de recuperación de incidentes');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('TASA_EXITO_DESPLIEGUES',        'DEVOPS',      'percent', 'Despliegues SUCCESS / total despliegues');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('INTERACCIONES_BOT',             'ENGAGEMENT',  'count',   'Mensajes procesados por el bot por día');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('DISPONIBILIDAD_SERVICIO',       'RELIABILITY', 'percent', 'Uptime calculado desde incidentes CRITICAL/HIGH');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('USO_CPU',                       'INFRA',       'percent', 'Uso promedio de CPU reportado por agente');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('USO_MEMORIA',                   'INFRA',       'percent', 'Uso promedio de memoria RAM reportado por agente');

INSERT INTO KPI_TYPES (NAME, CATEGORY, UNIT, DESCRIPTION)
VALUES ('INCIDENTES_SEGURIDAD',          'SECURITY',    'count',   'Incidentes con TYPE=SECURITY registrados');

/* ============================================================
   13. KPI_VALUES
   ============================================================ */
INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (1, 'SPRINT', 1, 3, TIMESTAMP '2025-01-19 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (1, 'SPRINT', 2, 3, TIMESTAMP '2025-02-02 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (1, 'SPRINT', 4, 2, TIMESTAMP '2025-01-26 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (2, 'SPRINT', 1, 100.00, TIMESTAMP '2025-01-19 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (2, 'SPRINT', 2, 75.00, TIMESTAMP '2025-02-02 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (2, 'SPRINT', 4, 100.00, TIMESTAMP '2025-01-26 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (3, 'SPRINT', 3, 1, TIMESTAMP '2025-02-06 12:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (4, 'PROJECT', 1, 66.67, TIMESTAMP '2025-02-05 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (4, 'PROJECT', 2, 50.00, TIMESTAMP '2025-02-05 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (5, 'PROJECT', 1, 2, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (5, 'PROJECT', 2, 1, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (6, 'SPRINT', 1, 1, TIMESTAMP '2025-01-19 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (6, 'SPRINT', 2, 2, TIMESTAMP '2025-02-02 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (7, 'PROJECT', 1, 47.50, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (7, 'PROJECT', 2, 120.00, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (8, 'PROJECT', 1, 80.00, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (8, 'PROJECT', 2, 100.00, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, VALUE, RECORDED_AT)
VALUES (9, 'GLOBAL', 38, TIMESTAMP '2025-02-04 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, VALUE, RECORDED_AT)
VALUES (9, 'GLOBAL', 51, TIMESTAMP '2025-02-05 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (10, 'SPRINT', 1, 99.95, TIMESTAMP '2025-01-19 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, SPRINT_ID, VALUE, RECORDED_AT)
VALUES (10, 'SPRINT', 2, 99.72, TIMESTAMP '2025-02-02 23:59:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (11, 'PROJECT', 1, 68.40, TIMESTAMP '2025-02-06 10:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (11, 'PROJECT', 1, 72.10, TIMESTAMP '2025-02-06 11:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (12, 'PROJECT', 1, 54.30, TIMESTAMP '2025-02-06 10:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (12, 'PROJECT', 1, 57.80, TIMESTAMP '2025-02-06 11:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (13, 'PROJECT', 1, 1, TIMESTAMP '2025-02-06 00:00:00');

INSERT INTO KPI_VALUES (KPI_TYPE_ID, SCOPE_TYPE, PROJECT_ID, VALUE, RECORDED_AT)
VALUES (13, 'PROJECT', 2, 0, TIMESTAMP '2025-02-06 00:00:00');

/* ============================================================
   14. LLM_ANALYSIS
   ============================================================ */
INSERT INTO LLM_ANALYSIS (SCOPE_TYPE, SPRINT_ID, ANOMALY_DETECTED, ANOMALY_TYPE, CONFIDENCE_SCORE, RECOMMENDATION)
VALUES ('SPRINT', 2, 'Y', 'SPRINT_CARRYOVER', 87.50,
        'La tarea "Integración con Telegram Bot API" fue arrastrada del Sprint 2 al Sprint 3. Se recomienda revisar la estimación de esfuerzo y dividir en subtareas más pequeñas.');

INSERT INTO LLM_ANALYSIS (SCOPE_TYPE, PROJECT_ID, ANOMALY_DETECTED, ANOMALY_TYPE, CONFIDENCE_SCORE, RECOMMENDATION)
VALUES ('PROJECT', 1, 'Y', 'BUG_REGRESSION', 91.20,
        'Se detectó regresión en el módulo de autenticación OAuth. El bug fue marcado como DONE y reabierto en menos de 24h. Considerar ampliar cobertura de pruebas unitarias.');

INSERT INTO LLM_ANALYSIS (SCOPE_TYPE, USER_ID, ANOMALY_DETECTED, ANOMALY_TYPE, CONFIDENCE_SCORE, RECOMMENDATION)
VALUES ('USER', 2, 'N', NULL, 95.00,
        'Luis Ramirez mantiene una velocidad constante de entrega. No se detectan anomalías en su ritmo de trabajo.');

INSERT INTO LLM_ANALYSIS (SCOPE_TYPE, PROJECT_ID, ANOMALY_DETECTED, ANOMALY_TYPE, CONFIDENCE_SCORE, RECOMMENDATION)
VALUES ('PROJECT', 1, 'Y', 'HIGH_CPU_USAGE', 78.30,
        'El uso de CPU superó el 70% en dos mediciones consecutivas. Revisar queries sin índice y considerar escalado horizontal del servicio.');

INSERT INTO LLM_ANALYSIS (SCOPE_TYPE, ANOMALY_DETECTED, CONFIDENCE_SCORE, RECOMMENDATION)
VALUES ('GLOBAL', 'N', 99.00,
        'El sistema opera dentro de parámetros normales. Las interacciones del bot aumentaron un 34% respecto al día anterior — tendencia positiva de adopción.');

/* ============================================================
   15. DEPLOYMENTS
   ============================================================ */
INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.0.0', 'DEV',        'SUCCESS',     TIMESTAMP '2025-01-10 14:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.0.0', 'QA',         'SUCCESS',     TIMESTAMP '2025-01-12 15:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.0.0', 'STAGING',    'SUCCESS',     TIMESTAMP '2025-01-15 16:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.0.0', 'PRODUCTION', 'SUCCESS',     TIMESTAMP '2025-01-19 20:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.1.0', 'DEV',        'SUCCESS',     TIMESTAMP '2025-01-25 10:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.1.0', 'QA',         'FAILED',      TIMESTAMP '2025-01-26 11:00:00', 35.00);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.1.1', 'QA',         'SUCCESS',     TIMESTAMP '2025-01-27 13:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.1.1', 'STAGING',    'SUCCESS',     TIMESTAMP '2025-01-28 15:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.1.1', 'PRODUCTION', 'SUCCESS',     TIMESTAMP '2025-02-02 21:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, 'v1.2.0', 'DEV',        'IN_PROGRESS', TIMESTAMP '2025-02-06 09:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (2, 'v0.9.0', 'DEV',        'SUCCESS',     TIMESTAMP '2025-01-20 10:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (2, 'v0.9.0', 'PRODUCTION', 'SUCCESS',     TIMESTAMP '2025-01-26 20:00:00', NULL);

/* ============================================================
   16. INCIDENTS
   ============================================================ */
INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, RESOLVED_AT)
VALUES (1, 'PERFORMANCE',
        'Latencia elevada en endpoint /api/tasks durante hora pico. P95 superó 3 segundos.',
        'HIGH', TIMESTAMP '2025-01-22 14:30:00', TIMESTAMP '2025-01-22 15:15:00');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, RESOLVED_AT)
VALUES (1, 'SECURITY',
        'Intento de acceso no autorizado detectado en endpoint /api/admin desde IP externa.',
        'CRITICAL', TIMESTAMP '2025-01-28 03:10:00', TIMESTAMP '2025-01-28 04:00:00');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, RESOLVED_AT)
VALUES (1, 'BUG',
        'Token JWT expirado no retorna 401 correctamente en algunos clientes iOS.',
        'MEDIUM', TIMESTAMP '2025-02-05 10:00:00', TIMESTAMP '2025-02-05 11:00:00');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, RESOLVED_AT)
VALUES (1, 'DEPLOYMENT',
        'Fallo en pipeline de QA al desplegar v1.1.0. Error en script de migración de BD.',
        'HIGH', TIMESTAMP '2025-01-26 11:00:00', TIMESTAMP '2025-01-26 12:30:00');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, RESOLVED_AT)
VALUES (2, 'PERFORMANCE',
        'Job nocturno de KPIs tardó 4 veces más de lo esperado por falta de índice.',
        'MEDIUM', TIMESTAMP '2025-01-25 02:00:00', TIMESTAMP '2025-01-25 03:00:00');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, RESOLVED_AT)
VALUES (1, 'PERFORMANCE',
        'Incremento sostenido en uso de CPU por encima del 70% desde las 09:00.',
        'HIGH', TIMESTAMP '2025-02-06 09:00:00', NULL);

/* ============================================================
   17. BOT_INTERACTIONS
   ============================================================ */
INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (2, '/tareas pendientes',
        'Tienes 2 tareas activas: "Integración Telegram Bot API" (IN_PROGRESS) y "Corrección bug OAuth" (REOPENED).',
        TIMESTAMP '2025-02-05 09:15:00');

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (3, '/sprint actual',
        'Sprint 3 del Proyecto Alpha está activo (03-Feb al 16-Feb). Progreso: 1/3 tareas completadas.',
        TIMESTAMP '2025-02-05 09:30:00');

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (1, '/incidentes abiertos',
        'Hay 1 incidente abierto: CPU elevada en Proyecto Alpha (SEVERITY: HIGH) desde las 09:00.',
        TIMESTAMP '2025-02-06 10:05:00');

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (1, '/kpi cumplimiento sprint 2',
        'Sprint 2 - Proyecto Alpha: Cumplimiento 75% (3 de 4 tareas completadas). 1 tarea arrastrada al Sprint 3.',
        TIMESTAMP '2025-02-06 10:20:00');

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (4, '/despliegues produccion',
        'Proyecto Beta: 1 despliegue a PRODUCTION exitoso. Última versión: v0.9.0 (26-Ene-2025).',
        TIMESTAMP '2025-02-06 11:00:00');

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (NULL, '/ayuda',
        'Comandos disponibles: /tareas, /sprint, /kpi, /incidentes, /despliegues, /dashboard.',
        TIMESTAMP '2025-02-06 11:30:00');

/* ============================================================
   18. AUDIT_LOG
   ============================================================ */
INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (1, 'CREATE', 'PROJECTS', 1, '192.168.1.10');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (1, 'CREATE', 'SPRINTS', 1, '192.168.1.10');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (1, 'CREATE', 'TASKS', 7, '192.168.1.10');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (1, 'UPDATE', 'TASKS', 7, '192.168.1.10');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (3, 'UPDATE', 'TASKS', 10, '192.168.1.25');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (2, 'UPDATE', 'DEPLOYMENTS', 6, '10.0.0.5');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (NULL, 'LOGIN_ATTEMPT', 'USER_CREDENTIALS', NULL, '203.0.113.42');

INSERT INTO AUDIT_LOG (USER_ID, ACTION_TYPE, ENTITY_NAME, ENTITY_ID, IP_ADDRESS)
VALUES (1, 'CREATE', 'INCIDENTS', 2, '192.168.1.10');

COMMIT;