/* ============================================================
   ORACLE JAVA BOT -  DATABASE SCHEMA
   ============================================================ */

---------------------------------------------------------------
-- 1️ ROLES
---------------------------------------------------------------
CREATE TABLE ROLES (
    ROLE_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROLE_NAME   VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(200)
);

---------------------------------------------------------------
-- 2️ TEAMS
---------------------------------------------------------------
CREATE TABLE TEAMS (
    TEAM_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(300)
);

---------------------------------------------------------------
-- 3️ USERS
---------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME   VARCHAR2(150) NOT NULL,
    EMAIL       VARCHAR2(150) NOT NULL UNIQUE,
    TELEGRAM_ID VARCHAR2(100) UNIQUE,
    ROLE_ID     NUMBER NOT NULL,
    TEAM_ID     NUMBER,
    STATUS      VARCHAR2(20) DEFAULT 'ACTIVE'
                CHECK (STATUS IN ('ACTIVE','INACTIVE','LOCKED')),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP,

    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID),

    CONSTRAINT FK_USER_TEAM FOREIGN KEY (TEAM_ID)
        REFERENCES TEAMS(TEAM_ID)
);

---------------------------------------------------------------
-- 4️ USER CREDENTIALS 
---------------------------------------------------------------
CREATE TABLE USER_CREDENTIALS (
    CREDENTIAL_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL UNIQUE,
    USERNAME        VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(255) NOT NULL,
    LAST_LOGIN      TIMESTAMP,
    FAILED_ATTEMPTS NUMBER DEFAULT 0,
    ACCOUNT_LOCKED  CHAR(1) DEFAULT 'N'
                    CHECK (ACCOUNT_LOCKED IN ('Y','N')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CREDENTIAL_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

---------------------------------------------------------------
-- 5️ SPRINTS
---------------------------------------------------------------
CREATE TABLE SPRINTS (
    SPRINT_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    START_DATE  DATE NOT NULL,
    END_DATE    DATE NOT NULL,
    STATUS      VARCHAR2(20) DEFAULT 'ACTIVE'
                CHECK (STATUS IN ('PLANNED','ACTIVE','CLOSED'))
);

---------------------------------------------------------------
-- 6️ TASKS
---------------------------------------------------------------
CREATE TABLE TASKS (
    TASK_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE       VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB,
    STATUS      VARCHAR2(30) DEFAULT 'PENDING'
                CHECK (STATUS IN ('PENDING','IN_PROGRESS','DONE','CANCELLED')),
    PRIORITY    VARCHAR2(20)
                CHECK (PRIORITY IN ('LOW','MEDIUM','HIGH')),
    CREATED_BY  NUMBER NOT NULL,
    ASSIGNED_TO NUMBER NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP,
    DUE_DATE    DATE,

    CONSTRAINT FK_TASK_CREATED FOREIGN KEY (CREATED_BY)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_TASK_ASSIGNED FOREIGN KEY (ASSIGNED_TO)
        REFERENCES USERS(USER_ID)
);

---------------------------------------------------------------
-- 7️ TASK STATUS HISTORY
---------------------------------------------------------------
CREATE TABLE TASK_STATUS_HISTORY (
    HISTORY_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TASK_ID     NUMBER NOT NULL,
    OLD_STATUS  VARCHAR2(30),
    NEW_STATUS  VARCHAR2(30),
    CHANGED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_HISTORY_TASK FOREIGN KEY (TASK_ID)
        REFERENCES TASKS(TASK_ID)
);

---------------------------------------------------------------
-- 8️ TASK - SPRINT RELATION
---------------------------------------------------------------
CREATE TABLE TASK_SPRINT (
    TASK_ID   NUMBER NOT NULL,
    SPRINT_ID NUMBER NOT NULL,

    CONSTRAINT PK_TASK_SPRINT PRIMARY KEY (TASK_ID, SPRINT_ID),

    CONSTRAINT FK_TS_TASK FOREIGN KEY (TASK_ID)
        REFERENCES TASKS(TASK_ID),

    CONSTRAINT FK_TS_SPRINT FOREIGN KEY (SPRINT_ID)
        REFERENCES SPRINTS(SPRINT_ID)
);

---------------------------------------------------------------
-- 9️ KPI TYPES
---------------------------------------------------------------
CREATE TABLE KPI_TYPES (
    KPI_TYPE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(150) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(500),
    CATEGORY    VARCHAR2(50),
    UNIT        VARCHAR2(50)
);

---------------------------------------------------------------
-- 10 KPI VALUES
---------------------------------------------------------------
CREATE TABLE KPI_VALUES (
    KPI_VALUE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KPI_TYPE_ID  NUMBER NOT NULL,
    USER_ID      NUMBER,
    SPRINT_ID    NUMBER,
    VALUE        NUMBER(12,4) NOT NULL,
    RECORDED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_KPI_TYPE FOREIGN KEY (KPI_TYPE_ID)
        REFERENCES KPI_TYPES(KPI_TYPE_ID),

    CONSTRAINT FK_KPI_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_KPI_SPRINT FOREIGN KEY (SPRINT_ID)
        REFERENCES SPRINTS(SPRINT_ID)
);

---------------------------------------------------------------
-- 1️1️ KPI THRESHOLDS
---------------------------------------------------------------
CREATE TABLE KPI_THRESHOLDS (
    THRESHOLD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KPI_TYPE_ID  NUMBER NOT NULL,
    MIN_VALUE    NUMBER(12,4),
    MAX_VALUE    NUMBER(12,4),
    ROLE_ID      NUMBER,

    CONSTRAINT FK_THRESHOLD_KPI FOREIGN KEY (KPI_TYPE_ID)
        REFERENCES KPI_TYPES(KPI_TYPE_ID),

    CONSTRAINT FK_THRESHOLD_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
);

---------------------------------------------------------------
-- 1️2️ LLM ANALYSIS
---------------------------------------------------------------
CREATE TABLE LLM_ANALYSIS (
    ANALYSIS_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER,
    SPRINT_ID        NUMBER,
    ANOMALY_DETECTED CHAR(1)
                     CHECK (ANOMALY_DETECTED IN ('Y','N')),
    ANOMALY_TYPE     VARCHAR2(100),
    CONFIDENCE_SCORE NUMBER(5,2),
    RECOMMENDATION   CLOB,
    ANALYSIS_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ANALYSIS_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_ANALYSIS_SPRINT FOREIGN KEY (SPRINT_ID)
        REFERENCES SPRINTS(SPRINT_ID)
);

---------------------------------------------------------------
-- 1️3️ NOTIFICATIONS
---------------------------------------------------------------
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    MESSAGE         CLOB NOT NULL,
    SENT_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS          VARCHAR2(20) DEFAULT 'SENT'
                    CHECK (STATUS IN ('SENT','FAILED','READ')),

    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

---------------------------------------------------------------
-- 1️4 DEPLOYMENTS (DevOps)
---------------------------------------------------------------
CREATE TABLE DEPLOYMENTS (
    DEPLOYMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSION       VARCHAR2(50),
    ENVIRONMENT   VARCHAR2(50),
    STATUS        VARCHAR2(20)
                  CHECK (STATUS IN ('SUCCESS','FAILED','IN_PROGRESS')),
    DEPLOYED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------------
-- 1️5 AUDIT LOG
---------------------------------------------------------------
CREATE TABLE AUDIT_LOG (
    AUDIT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER,
    ACTION_TYPE VARCHAR2(100),
    ENTITY_NAME VARCHAR2(100),
    ENTITY_ID   NUMBER,
    ACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS  VARCHAR2(50),

    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);